### ISSUE TITLE
Link github repo to project website

### ISSUE THREAD

**Issue by patcon** [opendatakosovo/cee-asset-declarations#10]
http://assetdeclarations.transparencee.org/infographics

When I link projects on our civic tech slack, i often prefer to just link the code first, and allow user to follow through to website.

More generally, would be great if these resources cross-references one another prominently (on the website, some relatively prominent header/footer link to "Source code on GitHub").

And thanks for this resource!

**Comment by KrzysztofMadejski** [comment]
Done! Link in the README and the footer of the site.
